stages:
  - build
  - test
  - build-image
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/nijatkhanaliev/ms-account
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

before_script:
  - export GRADLE_USER_HOME=$GRADLE_USER_HOME

cache:
  key: gradle-cache
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  image: gradle:8.4-jdk21
  script:
    - gradle clean assemble
  artifacts:
    paths:
      - build/libs/
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'
      when: never

test:
  stage: test
  image: gradle:8.4-jdk21
  services:
    - name: docker:24.0.2-dind
      alias: docker
  script:
    - docker info
    - gradle test
  rules:
    - if: '$CI_COMMIT_BRANCH'


build-image:
  stage: build-image
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    - ls build/libs/*.jar
    - docker build -f Dockerfile -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main

deploy:
  stage: deploy
  script:  echo "Deploying the application..."
  only:
    - main
